server:
  port: 8081
spring:
  devtools:
    livereload:
      port: 35730

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.233.133:3306/oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
    username: root
    password: root
    hikari:
      # 连接池名
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认60000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-init-sql: SELECT 1


  redis:
    # 超时时间
    timeout: 10000ms
    # 服务器地址
    host: 192.168.233.133
    # 服务器端口
    port: 6379
    # 数据库
    database: 0
    # 密码
    password: 123456
    lettuce:
      pool:
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: 192.168.233.133
    # 端口
    port: 5672
    # 消息确然回调
    publisher-confirm-type: correlated
    # 消息失败回调
    publisher-returns: true

# Mybatis-plus配置
mybatis-plus:
  mapper-l  ocations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: cn.zzw.server.pojo
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full

# mybatis SQL 打印
logging:
  level:
    cn.zzw.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer

#添加对OSS服务的配置
oss:
  access-key: LTAI5tCezxZS2Agqz7RQMKn6
  secret-key: DFyoeUbrur4LlgRVKYr6o5DSjRyc2q
  endpoint: oss-cn-guangzhou.aliyuncs.com
  bucket: oa-09kj
